### ISSUE TITLE
remove_id_prefix: undefined method `delete_prefix' in interop_formatter

### ISSUE THREAD

**Issue by jiridanek** [rh-messaging/cli-proton-ruby#54]
https://master-jenkins-csb-amq-clients-qe.cloud.paas.psi.redhat.com/view/AMQ_Clients/job/tests/job/linux/job/dtests-amq-clients-interoperability/105/

```
'stderr': ['/var/dtests/node_data/clients/cli-proton-ruby/lib/formatters/interop_formatter.rb:53:in '
                "`remove_id_prefix': undefined method `delete_prefix' for "
                '"ID:2a37626a-8cd6-42bd-b8f8-c67b12f5ef91:1:1:1-1":String '
                '(NoMethodError)',
                '\tfrom '
                '/var/dtests/node_data/clients/cli-proton-ruby/lib/formatters/interop_formatter.rb:70:in '
                "`get_as_interop_dictionary'",
                '\tfrom '
                '/var/dtests/node_data/clients/cli-proton-ruby/lib/formatters/interop_formatter.rb:95:in '
                "`print'",
                '\tfrom '
                '/var/dtests/node_data/clients/cli-proton-ruby/lib/handlers/sr_common_handler.rb:87:in '
                "`print_message'",
                '\tfrom '
                '/var/dtests/node_data/clients/cli-proton-ruby/lib/handlers/receiver_handler.rb:156:in '
                "`on_message'",
                '\tfrom '
                '/usr/share/gems/gems/qpid_proton-0.33.0/lib/handler/adapter.rb:74:in '
                "`forward'",
                '\tfrom '
                '/usr/share/gems/gems/qpid_proton-0.33.0/lib/handler/messaging_adapter.rb:27:in '
                "`delegate'",
                '\tfrom '
                '/usr/share/gems/gems/qpid_proton-0.33.0/lib/handler/messaging_adapter.rb:108:in '
                "`on_delivery'",
                '\tfrom '
                '/usr/share/gems/gems/qpid_proton-0.33.0/lib/core/event.rb:94:in '
                "`dispatch'",
                '\tfrom '
                '/usr/share/gems/gems/qpid_proton-0.33.0/lib/core/connection_driver.rb:194:in '
                "`block in dispatch'",
                '\tfrom '
                '/usr/share/gems/gems/qpid_proton-0.33.0/lib/core/connection_driver.rb:78:in '
                "`each_event'",
                '\tfrom '
                '/usr/share/gems/gems/qpid_proton-0.33.0/lib/core/connection_driver.rb:188:in '
                "`dispatch'",
                '\tfrom '
                '/usr/share/gems/gems/qpid_proton-0.33.0/lib/core/container.rb:270:in '
                "`dispatch'",
                '\tfrom '
                '/usr/share/gems/gems/qpid_proton-0.33.0/lib/core/connection_driver.rb:204:in '
                "`process'",
                '\tfrom '
                '/usr/share/gems/gems/qpid_proton-0.33.0/lib/core/container.rb:267:in '
                "`process'",
                '\tfrom '
                '/usr/share/gems/gems/qpid_proton-0.33.0/lib/core/container.rb:419:in '
                "`block in run_one'",
                '\tfrom '
                '/usr/share/gems/gems/qpid_proton-0.33.0/lib/core/container.rb:432:in '
                "`maybe_panic'",
                '\tfrom '
                '/usr/share/gems/gems/qpid_proton-0.33.0/lib/core/container.rb:419:in '
                "`run_one'",
                '\tfrom '
                '/usr/share/gems/gems/qpid_proton-0.33.0/lib/core/container.rb:197:in '
                "`run'",
                '\tfrom '
                '/var/dtests/node_data/clients/cli-proton-ruby/lib/receiver_client.rb:56:in '
                "`initialize'",
                '\tfrom '
                '/var/dtests/node_data/clients/cli-proton-ruby-receiver:21:in '
                "`new'",
                '\tfrom '
                '/var/dtests/node_data/clients/cli-proton-ruby-receiver:21:in '
                "`<main>'"],
```

**Comment by pematous** [comment]
resolved by: https://github.com/rh-messaging/cli-proton-ruby/commit/8b547601f2c3d39417c0f017ac5d4e64741e67ab
